# Generated by Django 4.1.5 on 2023-02-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='age',
            new_name='age1',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='gender',
            new_name='gender1',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='experience',
            new_name='phone1',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='dob',
            new_name='roles1',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_details',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
    ]
