# Generated by Django 4.1.5 on 2023-02-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_address_doctor_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='roles1',
            field=models.TextField(),
        ),
    ]
